version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis-secure
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./users.acl:/usr/local/etc/redis/users.acl
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
